# Generated by Django 3.0.5 on 2020-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Student',
            fields=[
                ('s_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('semester', models.IntegerField(max_length=1)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=40, unique=True)),
                ('Phone', models.IntegerField(max_length=10, unique=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
