# Generated by Django 3.0.5 on 2020-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT_DATA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_student',
            name='Phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
