# Generated by Django 3.0.5 on 2020-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT_DATA', '0003_student_signup_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_signup_record',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
