# Generated by Django 3.0.5 on 2020-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT_DATA', '0004_auto_20200603_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_student',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
