# Generated by Django 3.0.5 on 2020-06-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT_DATA', '0008_auto_20200603_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Student',
        ),
        migrations.DeleteModel(
            name='Student_signup_record',
        ),
    ]
