# Generated by Django 3.0.5 on 2020-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_image',
            fields=[
                ('s_img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_add', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
