# Generated by Django 3.0.5 on 2020-06-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0002_auto_20200609_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_image',
            name='s_img_id',
        ),
    ]
