# Generated by Django 3.0.5 on 2020-06-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0005_auto_20200609_0728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='store_img',
        ),
    ]
