# Generated by Django 3.0.5 on 2020-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0006_auto_20200609_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_img',
            name='img_add',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
