# Generated by Django 3.0.5 on 2020-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0007_auto_20200609_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_img',
            name='img_add',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
