# Generated by Django 3.0.5 on 2020-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0008_auto_20200609_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_img',
            name='id',
        ),
        migrations.AddField(
            model_name='store_img',
            name='img_id',
            field=models.IntegerField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
