# Generated by Django 3.0.5 on 2020-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0009_auto_20200609_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='STOR_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_add', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
