# Generated by Django 3.0.5 on 2020-06-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0010_stor_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store_img',
        ),
    ]
