# Generated by Django 3.0.5 on 2020-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP2', '0002_exam_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_result',
            name='Multiple_choice_result',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='True_false_result',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
