# Generated by Django 3.0.5 on 2020-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP2', '0003_auto_20200701_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_result',
            name='True_false_result',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
