# Generated by Django 3.0.5 on 2020-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Student',
            fields=[
                ('s_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=40, unique=True)),
                ('Phone', models.CharField(max_length=12, unique=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_signup_record',
            fields=[
                ('college_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(default=0, max_length=15)),
            ],
        ),
    ]
