# Generated by Django 3.0.5 on 2020-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0002_auto_20200604_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_student1',
            name='s_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_signup_record1',
            name='college_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
