# Generated by Django 3.0.5 on 2020-06-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0004_one_time_access_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_signup_record1',
            name='email',
        ),
        migrations.AddField(
            model_name='student_signup_record1',
            name='D_O_B',
            field=models.DateField(default='04-12-2000'),
        ),
    ]
