# Generated by Django 3.0.5 on 2020-06-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0015_auto_20200616_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_signup_record1',
            name='D_O_B',
        ),
    ]
