# Generated by Django 3.0.5 on 2020-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0016_remove_student_signup_record1_d_o_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_signup_record1',
            name='email',
            field=models.CharField(default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
