# Generated by Django 3.0.5 on 2020-06-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0018_student_signup_record2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_signup_record2',
            name='D_O_B',
            field=models.DateField(),
        ),
    ]
