# Generated by Django 3.0.5 on 2020-06-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0020_student_signup_record3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_signup_record1',
        ),
        migrations.DeleteModel(
            name='Student_signup_record2',
        ),
    ]
