# Generated by Django 3.0.5 on 2020-06-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0023_auto_20200616_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_signup_r',
            fields=[
                ('college_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('semester', models.IntegerField()),
                ('password', models.CharField(default=0, max_length=15)),
            ],
        ),
    ]
