# Generated by Django 3.0.5 on 2020-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0024_student_signup_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_signup_record_store',
            fields=[
                ('s_college_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=40, unique=True)),
                ('s_semester', models.IntegerField()),
                ('s_password', models.CharField(default=0, max_length=15)),
            ],
        ),
    ]
