# Generated by Django 3.0.5 on 2020-06-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0025_student_signup_record_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_signup',
        ),
        migrations.DeleteModel(
            name='Student_signup_r',
        ),
        migrations.DeleteModel(
            name='Student_signup_record_store',
        ),
    ]
