# Generated by Django 3.0.5 on 2020-06-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGNUP1', '0027_man'),
    ]

    operations = [
        migrations.DeleteModel(
            name='man',
        ),
        migrations.DeleteModel(
            name='My_Student1',
        ),
        migrations.DeleteModel(
            name='one_time_access_check',
        ),
    ]
