# Generated by Django 3.0.5 on 2020-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fill_Student',
            fields=[
                ('s_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
