# Generated by Django 3.0.5 on 2020-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAGE_G', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_store',
            name='img_add',
            field=models.ImageField(blank=True, default='/static/login.jpeg', upload_to='pics'),
        ),
    ]
