# Generated by Django 3.0.5 on 2020-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMAGE_G', '0003_auto_20200611_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_store',
            name='img_add',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
